import type { InsightCategory } from "@/db/schema";

/**
 * Starter articles. They are general, factual guidance (no client claims or results).
 * They are seeded with status "review" so Dylan approves them before they go live.
 */
export const STARTER_INSIGHTS: {
  slug: string;
  title: string;
  summary: string;
  category: InsightCategory;
  readingMinutes: number;
  body: string;
  faq: { question: string; answer: string }[];
}[] = [
  {
    slug: "seo-geo-aeo-explained",
    title: "SEO, GEO and AEO explained for B2B businesses",
    summary:
      "What each term actually means, how they overlap, and what to do first if you want to be found on Google and in AI answers.",
    category: "seo",
    readingMinutes: 6,
    body: `Buyers now research in two places: traditional search results and AI assistants that answer questions directly. Three terms describe the work of being visible in both. They overlap more than the jargon suggests.

## SEO: search engine optimisation

SEO is the work of making your website easy for search engines to crawl, understand and rank. It covers three layers:

- **Technical foundations**: the site loads fast, works on mobile, can be crawled and indexed, and has a sitemap.
- **Relevance**: each important page clearly targets what a buyer searches for, with a descriptive title, heading and content.
- **Authority**: other credible sites and profiles refer to you, and your content is useful enough to be referenced.

## AEO: answer engine optimisation

AEO focuses on **questions**. Search engines and assistants increasingly show a direct answer rather than a list of links. Pages that clearly answer the questions buyers ask are more likely to be used. Examples are "How long does a pump overhaul take?" and "What does ISO 9001 certification involve for a small manufacturer?"

In practice, AEO means:

1. Collecting the questions your sales team hears every week.
2. Answering each one clearly and specifically on the most relevant page.
3. Structuring those answers with headings (and FAQ structured data where the page genuinely is a list of questions).

## GEO: generative engine optimisation

GEO is about how AI systems understand your business as an **entity**: who you are, what you do, where you operate and why you are credible. Nobody controls what an AI assistant says. You can, however, make accurate information about your business easy to find and hard to misunderstand:

- consistent company facts across your website, LinkedIn, Google Business Profile and directories
- structured data describing your organisation, services and locations
- an About page that makes expertise and accountability clear
- genuinely useful content that other sources reference

## Where to start

For most B2B companies the order is simple. Fix the technical basics, make your service pages clearly describe what you do and for whom, then build a steady habit of answering real buyer questions. That work serves SEO, AEO and GEO at the same time.

A free visibility snapshot is a quick way to see which of these foundations are already in place.`,
    faq: [
      {
        question: "Is GEO different from SEO?",
        answer:
          "GEO builds on SEO. It focuses on making your business facts and expertise clear and consistent so AI systems can understand and reference you, while SEO covers crawlability, relevance and authority in search results.",
      },
      {
        question: "Can anyone guarantee my business appears in AI answers?",
        answer:
          "No. AI answers are generated by third-party systems. You can improve the likelihood by making accurate, authoritative information easy to find, but no one can guarantee inclusion.",
      },
      {
        question: "What should a B2B company do first?",
        answer:
          "Fix technical basics, make each service page clearly describe what you do and for whom, and start answering the questions buyers ask your sales team.",
      },
    ],
  },
  {
    slug: "why-b2b-websites-dont-generate-enquiries",
    title: "Why most B2B websites don't generate enquiries (and how to fix it)",
    summary:
      "Six common reasons good businesses get few enquiries from their website, with a practical fix for each.",
    category: "business_growth",
    readingMinutes: 5,
    body: `Many strong B2B businesses have websites that look fine but rarely produce a new conversation. The causes are usually the same few issues.

## 1. The site describes the company, not the customer's problem

Visitors arrive with a problem. If the first screen says "Excellence in engineering since 1998", they have to work out whether you can help. Lead with what you do, for whom, and the outcome.

## 2. Nobody can find it

A site that ranks only for your company name only reaches people who already know you. Service pages need to match the words buyers actually search for, including location where it matters.

## 3. There is no obvious next step

"Contact us" at the bottom of the page is not a call to action. Give one clear primary action, such as "Book a site assessment" or "Request a quote", and repeat it where a reader naturally decides.

## 4. Proof is missing

B2B buyers are managing risk. Specific case studies, named clients (with permission), certifications and real testimonials reduce that risk. Generic praise does not.

## 5. Mobile is an afterthought

Decision makers often shortlist suppliers on a phone. Slow pages, tiny text and forms that are hard to complete on mobile quietly lose enquiries.

## 6. Nothing is measured

Without analytics and enquiry tracking you can't tell which pages or channels work, so improvements are guesswork. Measure enquiries as conversions from day one.

## The fix is a system, not a redesign

A new design rarely solves these on its own. What works is a cycle: find the gaps, fix the highest-impact ones, measure, and repeat every month.`,
    faq: [
      {
        question: "How quickly can website changes increase enquiries?",
        answer:
          "Conversion fixes (clear calls to action, better forms) can show results within weeks. Search visibility improvements typically take several months to build.",
      },
      {
        question: "Do we need a new website?",
        answer:
          "Not always. Many sites improve substantially through better content, structure, calls to action and measurement without a rebuild.",
      },
    ],
  },
  {
    slug: "ai-automation-for-service-businesses",
    title: "Practical AI and automation for service businesses",
    summary:
      "Where automation genuinely saves time in a professional services business, and where a human should stay in control.",
    category: "automation",
    readingMinutes: 5,
    body: `Automation is most valuable when it removes repetitive work so people can spend more time with customers and on decisions. It isn't about replacing your team.

## Good first candidates

- **Enquiry handling**: capture, route and acknowledge every enquiry immediately, with the details your team needs.
- **Follow-ups**: reminders so quotes and proposals don't go quiet.
- **Reporting**: monthly reports that assemble themselves from your systems, so people interpret rather than compile.
- **Document processing**: extracting the key fields from forms, orders or applications.
- **Internal knowledge**: a searchable source of truth for procedures and answers staff need every day.

## Keep humans in the loop where it matters

A useful rule is to decide, for each automated step, whether the system should **suggest**, **prepare for approval**, or **act on its own**. Anything that reaches a customer, commits money or changes a contract should start with human approval. As a workflow proves reliable, you can safely move it towards more automation.

## How to start

1. List the tasks your team repeats every week.
2. Estimate the hours each one takes.
3. Pick one with clear rules and a clear owner.
4. Automate it with a human checkpoint, measure the result, then move to the next.

Small, well-controlled automations compound quickly.`,
    faq: [
      {
        question: "Will automation replace my staff?",
        answer:
          "The aim is to remove repetitive work so people can focus on customers, judgement and growth, not to replace them.",
      },
      {
        question: "Is AI safe to use with client information?",
        answer:
          "It can be, with the right controls: limiting what data each tool can access, keeping humans in the loop for client-facing output, and choosing providers with appropriate data-protection terms.",
      },
    ],
  },
];
